### ISSUE TITLE
How would I send a packet through HTML?

### ISSUE THREAD

**Issue by beniroquai** [hideakitai/MsgPack#9] opened 2022-02-22 17:41 UTC
Hey @hideakitai, thanks a lot for making this library available. 
I was wondering how I could send a package created using a JSON document through a HTTP Post. 

A (yet failing) code snippet I have so far is this:

```cpp
  serializeJsonPretty(jsonDocument, Serial);

  // Encode the arguments as msgpack
  MsgPack::Packer packer;
  packer.serialize(jsonDocument);
  const MsgPack::bin_t<uint8_t>& packet = packer.packet();
  Serial.println(packet);

  int httpResponseCode = http.POST(packet);
  Serial.println(httpResponseCode);
```
Thanks a lot for your help!

**Comment by hideakitai** [comment] 2022-02-23 00:22
Could you give me more information? Board name, full code, what the problem is, etc.

**Comment by beniroquai** [comment] 2022-02-23 00:32
I'm using an ESP32 and want to send a serialized stream to a webserver using msgpack. I have a json document with several entries:

```
{
  "_rtype": "ndarray",
  "_rdtype": "float32",
  "model_name": "cellpose-python",
  "_rshape": [
    1,
    25,
    25
  ],
  "_rvalue": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14]
```

that I would like to send to a python server that expects a bytestream. 
The python equivalent is this here:

```py
    message = 
        {
            "inputs": inputs,
            "model_name": model_name,
        }
    
    # Encode the arguments as msgpack
    data = msgpack.dumps(message)

    # Compress the data and send it via a post request to the server
    compressed_data = gzip.compress(data)
    response = requests.post(
        f"{server_url}/public/services/triton-client/execute",
        data=compressed_data,
        headers={
            "Content-Type": "application/msgpack",
            "Content-Encoding": "gzip",
        },
    )
```

The problem when compiling the above code in the Arduino IDE is the following:

```
exit status 1
no matching function for call to 'HardwareSerial::println(arduino::msgpack::bin_t<unsigned char>&)'
````

As the error states, I want to convert a msgpack object into a stream which obviously does not work. How would I send a serialized msgpack object via a HTTP Post? 

Thanks!

**Comment by hideakitai** [comment] 2022-02-23 00:55
The error message is caused by this line

```
Serial.println(packet);
```

Please comment out it and try again.

**Comment by beniroquai** [comment] 2022-02-23 13:11
Yes, I understand this, but I wanted to get the binary output stream of the packet and send this as a `char` (?) via HTTP. The `Serial.println()` was just for debugging purposes, but it obviously didn't work. How would you send a serialized `packet` over HTTP?

**Comment by hideakitai** [comment] 2022-02-24 07:27
I want complete code because I don't know what `http.POST` requires for the arguments. `packet.data()` returns `uint8_t*` but it won't be `char*` because `packet` is not null-terminated.

**Comment by hideakitai** [comment] 2022-03-07 04:04
I am closing this issue because no further information has been provided. Please feel free to reopen this.

**Closed as completed by hideakitai** 2022-03-07 04:04 UTC
